### ISSUE TITLE
Question about article "Managing dotfiles with GNU stow"

### ISSUE THREAD

**Issue by snowman** [alexpearce/dotfiles#2]
Link: [Managing dotfiles with GNU stow - Alex Pearce](https://alexpearce.me/2016/02/managing-dotfiles-with-stow/)

>   Running stow foo inside the dotfiles folder will then create a
>   symbolic link at ~/.config/foo/somefile, creating any intermediate
>   directories that don’t already exist.

The following statement is not correct:

> Creating any intermediate directories that don’t already exist.

From my test,
```bash
$ [ -d ~/.config/ ] && echo "It's a directory"
It's a directory

$ [ ! -e ~/.config/foo ] && echo "The file does not exist"
The file does not exist

$ mkdir -p ~/test-dotfiles/foo/.config/foo/
$ touch    ~/test-dotfiles/foo/.config/foo/foo.conf
$ cd       ~/test-dotfiles/
$ stow foo

# Expected ~/.config/foo/ as directory,
#          ~/.config/foo/foo.conf as symbolic link
#
# But,     ~/.config/foo is symbolic link
$ ls -l    ~/.config/foo
lrwxrwxrwx 1 aaa aaa 32 Oct 16 20:37 ~/.config/foo -> ../test-dotfiles/foo/.config/foo 
```

It's a link file instead, not creating any intermediate directories that don't already exist.

**Comment by alexpearce** [comment]
> Is creating any intermediate directories that don’t already exist. true?

You're right, it's not true. Stow actually tries to create as _few_ intermediate directories as possible. If it encounters an intermediate directory that doesn't already exist, it will create the symlink at _that_ point.

Thanks for pointing this mistake out. I'll keep this issue open as a reminder to fix the post.
